---
- name: Install requirements packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /tmp/docker.gpg

- name: Remove docker.gpg if exists
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent

- name: Import Docker GPG key
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg

- name: Set permissions for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    owner: root
    group: root
    mode: '0644'

- name: Determine host architecture
  set_fact:
    host_architecture_dpkg_format: "{{ 'amd64' if ansible_system == 'Linux' and ansible_architecture == 'x86_64' else 'unknown' }}"

- name: Create Docker repository file
  ansible.builtin.template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  vars:
    host_architecture_dpkg_format: "{{ host_architecture_dpkg_format | replace('\n', '') }}"

- name: Install docker 
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: Start and enable docker
  systemd:
    name: docker
    state: restarted
    enabled: yes